version: '3.8'

services:
  void-vm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: void-vm-main
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '6080:6080'
